// Command genpatterns generates the Python mirror of the Go-side
// InputSanitizer pattern table.
//
// The Go side is the authority: [security.DefaultPatterns] is the canonical
// source of every detection rule. This tool serialises that slice to
// `agents/security_patterns.py` so the Python sanitizer has byte-identical
// regex strings and pattern names without re-deriving them from prose.
//
// Usage:
//
//	go run ./cmd/genpatterns -out agents/security_patterns.py
//
// or via the Makefile target:
//
//	make generate-sanitizer-patterns
//
// The pattern-parity test in tests/unit/python/test_pattern_parity.py loads
// both sides and asserts they agree. If you edit [security.DefaultPatterns],
// re-run this generator and commit the resulting diff in the same PR — CI
// fails otherwise.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/mkhomutov/persatrix/internal/security"
)

func main() {
	out := flag.String("out", "agents/security_patterns.py", "Output Python module path")
	flag.Parse()

	src := render(security.DefaultPatterns)
	if err := os.WriteFile(*out, []byte(src), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *out, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d bytes to %s (%d patterns)\n", len(src), *out, len(security.DefaultPatterns))
}

// render serialises patterns to a Python module body. The output is
// deterministic — same input produces byte-identical bytes — so committing
// the file and re-running this tool should produce no diff.
func render(patterns []security.Pattern) string {
	var b strings.Builder
	b.WriteString("# Code generated by cmd/genpatterns. DO NOT EDIT.\n")
	b.WriteString("#\n")
	b.WriteString("# Source: internal/security/sanitize_patterns.go (var DefaultPatterns).\n")
	b.WriteString("# Regenerate via: make generate-sanitizer-patterns\n")
	b.WriteString("#\n")
	b.WriteString("# Pattern parity is enforced by tests/unit/python/test_pattern_parity.py.\n")
	b.WriteString("# If this file goes stale relative to the Go source, the parity test\n")
	b.WriteString("# fails until the generator is re-run and the diff committed.\n")
	b.WriteString("\n")
	b.WriteString("from __future__ import annotations\n")
	b.WriteString("\n")
	b.WriteString("import re\n")
	b.WriteString("from dataclasses import dataclass\n")
	b.WriteString("\n")
	b.WriteString("\n")
	b.WriteString("@dataclass(frozen=True)\n")
	b.WriteString("class _Pattern:\n")
	b.WriteString("    name: str\n")
	b.WriteString("    regex: str\n")
	b.WriteString("    description: str\n")
	b.WriteString("\n")
	b.WriteString("\n")
	b.WriteString("# DEFAULT_PATTERNS mirrors security.DefaultPatterns from the Go side.\n")
	b.WriteString("# Order, names, regex strings, and descriptions are byte-identical.\n")
	b.WriteString("DEFAULT_PATTERNS: list[_Pattern] = [\n")
	for _, p := range patterns {
		fmt.Fprintf(&b, "    _Pattern(\n")
		fmt.Fprintf(&b, "        name=%s,\n", pyRepr(p.Name))
		// Go regex syntax (RE2) is a subset compatible with Python `re`
		// for the patterns we actually use here (`(?i)`, `\b`, bounded
		// `.{0,N}`). We pin the Go-source string verbatim so any future
		// pattern that drifts surfaces in the parity test rather than
		// silently diverging.
		fmt.Fprintf(&b, "        regex=%s,\n", pyRepr(p.Regex.String()))
		fmt.Fprintf(&b, "        description=%s,\n", pyRepr(p.Description))
		fmt.Fprintf(&b, "    ),\n")
	}
	b.WriteString("]\n")
	b.WriteString("\n")
	b.WriteString("\n")
	b.WriteString("# Compiled forms are cached at module load. The Go side compiles via\n")
	b.WriteString("# regexp.MustCompile in package init; the Python equivalent is the\n")
	b.WriteString("# tuple below, evaluated once when this module is imported.\n")
	b.WriteString("COMPILED_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = tuple(\n")
	b.WriteString("    (p.name, re.compile(p.regex)) for p in DEFAULT_PATTERNS\n")
	b.WriteString(")\n")
	return b.String()
}

// pyRepr renders s as a Python double-quoted string literal. We avoid
// raw-string forms because Go's regex strings already escape backslashes
// once; doubling that with Python raw-strings would diverge from the Go
// source. The escape table covers the characters that appear in the
// pattern table — extending it for new escapes is cheaper than pulling in
// a JSON encoder for what is conceptually a trivial mapping.
func pyRepr(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
