// Command genpatterns generates the Python mirrors of the Go-side
// security surface that needs Go↔Python parity.
//
// Two outputs:
//
//   - The InputSanitizer pattern table — sourced from
//     [security.DefaultPatterns] — written to `agents/security_patterns.py`.
//   - The closed-set enums (ContextSource, SanitizerAction) — sourced from
//     [security.AllContextSources] and [security.AllSanitizerActions] —
//     written to `agents/security_enums.py`.
//
// The Go side is the authority for both. This tool serialises them into
// Python modules so the Python sanitizer has byte-identical regex strings,
// pattern names, and enum constants without re-deriving them from prose.
//
// Usage:
//
//	go run ./cmd/genpatterns \
//	    -out agents/security_patterns.py \
//	    -enums-out agents/security_enums.py
//
// or via the Makefile target:
//
//	make generate-sanitizer-patterns
//
// The pattern-parity test in tests/unit/python/test_pattern_parity.py loads
// both sides and asserts they agree. If you edit [security.DefaultPatterns]
// or the enum closed sets, re-run this generator and commit the resulting
// diff in the same PR — CI fails otherwise.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/mkhomutov/persatrix/internal/security"
)

func main() {
	out := flag.String("out", "agents/security_patterns.py", "Output Python module path for the pattern table")
	enumsOut := flag.String("enums-out", "agents/security_enums.py", "Output Python module path for ContextSource + SanitizerAction enums")
	flag.Parse()

	patternsSrc := renderPatterns(security.DefaultPatterns)
	if err := os.WriteFile(*out, []byte(patternsSrc), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *out, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d bytes to %s (%d patterns)\n", len(patternsSrc), *out, len(security.DefaultPatterns))

	enumsSrc := renderEnums(security.AllContextSources(), security.AllSanitizerActions())
	if err := os.WriteFile(*enumsOut, []byte(enumsSrc), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *enumsOut, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d bytes to %s (%d sources, %d actions)\n",
		len(enumsSrc), *enumsOut,
		len(security.AllContextSources()), len(security.AllSanitizerActions()),
	)
}

// renderPatterns serialises patterns to a Python module body. The output is
// deterministic — same input produces byte-identical bytes — so committing
// the file and re-running this tool should produce no diff.
func renderPatterns(patterns []security.Pattern) string {
	var b strings.Builder
	b.WriteString("# Code generated by cmd/genpatterns. DO NOT EDIT.\n")
	b.WriteString("#\n")
	b.WriteString("# Source: internal/security/sanitize_patterns.go (var DefaultPatterns).\n")
	b.WriteString("# Regenerate via: make generate-sanitizer-patterns\n")
	b.WriteString("#\n")
	b.WriteString("# Pattern parity is enforced by tests/unit/python/test_pattern_parity.py.\n")
	b.WriteString("# If this file goes stale relative to the Go source, the parity test\n")
	b.WriteString("# fails until the generator is re-run and the diff committed.\n")
	b.WriteString("\n")
	b.WriteString("from __future__ import annotations\n")
	b.WriteString("\n")
	b.WriteString("import re\n")
	b.WriteString("from dataclasses import dataclass\n")
	b.WriteString("\n")
	b.WriteString("\n")
	b.WriteString("@dataclass(frozen=True)\n")
	b.WriteString("class _Pattern:\n")
	b.WriteString("    name: str\n")
	b.WriteString("    regex: str\n")
	b.WriteString("    description: str\n")
	b.WriteString("\n")
	b.WriteString("\n")
	b.WriteString("# DEFAULT_PATTERNS mirrors security.DefaultPatterns from the Go side.\n")
	b.WriteString("# Order, names, regex strings, and descriptions are byte-identical.\n")
	b.WriteString("DEFAULT_PATTERNS: list[_Pattern] = [\n")
	for _, p := range patterns {
		fmt.Fprintf(&b, "    _Pattern(\n")
		fmt.Fprintf(&b, "        name=%s,\n", pyRepr(p.Name))
		// Go regex syntax (RE2) is a subset compatible with Python `re`
		// for the patterns we actually use here (`(?i)`, `\b`, bounded
		// `.{0,N}`). We pin the Go-source string verbatim so any future
		// pattern that drifts surfaces in the parity test rather than
		// silently diverging.
		fmt.Fprintf(&b, "        regex=%s,\n", pyRepr(p.Regex.String()))
		fmt.Fprintf(&b, "        description=%s,\n", pyRepr(p.Description))
		fmt.Fprintf(&b, "    ),\n")
	}
	b.WriteString("]\n")
	b.WriteString("\n")
	b.WriteString("\n")
	b.WriteString("# Compiled forms are cached at module load. The Go side compiles via\n")
	b.WriteString("# regexp.MustCompile in package init; the Python equivalent is the\n")
	b.WriteString("# tuple below, evaluated once when this module is imported.\n")
	b.WriteString("COMPILED_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = tuple(\n")
	b.WriteString("    (p.name, re.compile(p.regex)) for p in DEFAULT_PATTERNS\n")
	b.WriteString(")\n")
	return b.String()
}

// renderEnums serialises the closed-set enums to a Python module body. Same
// determinism guarantee as renderPatterns: byte-identical output for a given
// Go input.
//
// The constant names are derived from the value strings by upper-casing and
// prefixing — `internal` → `CONTEXT_SOURCE_INTERNAL`, `agent_output` →
// `CONTEXT_SOURCE_AGENT_OUTPUT`, `passthrough` → `SANITIZER_ACTION_PASSTHROUGH`.
// The Go enum value strings already use snake_case where multi-word, so a
// plain ToUpper round-trips correctly.
func renderEnums(sources []security.ContextSource, actions []security.SanitizerAction) string {
	var b strings.Builder
	b.WriteString("# Code generated by cmd/genpatterns. DO NOT EDIT.\n")
	b.WriteString("#\n")
	b.WriteString("# Source:\n")
	b.WriteString("#   - internal/security/context_source.go (ContextSource closed set)\n")
	b.WriteString("#   - internal/security/sanitize_action.go (SanitizerAction closed set)\n")
	b.WriteString("# Regenerate via: make generate-sanitizer-patterns\n")
	b.WriteString("#\n")
	b.WriteString("# Enum parity is enforced by tests/unit/python/test_pattern_parity.py.\n")
	b.WriteString("# Adding or renaming a Go-side enum value without re-running the\n")
	b.WriteString("# generator fails CI; the byte-level diff is the parity gate.\n")
	b.WriteString("\n")
	b.WriteString("from __future__ import annotations\n")
	b.WriteString("\n")
	b.WriteString("from typing import Final\n")
	b.WriteString("\n")
	b.WriteString("# ─── ContextSource closed set ─────────────────────────────────────────\n")
	b.WriteString("#\n")
	b.WriteString("# Mirrors Go's `internal/security/context_source.go`. The string values\n")
	b.WriteString("# are written verbatim into the audit log's `Detail.source` field on\n")
	b.WriteString("# both sides, so renaming silently breaks operator alerts.\n")
	b.WriteString("\n")
	for _, s := range sources {
		fmt.Fprintf(&b, "%s: Final[str] = %s\n", contextSourceConstName(string(s)), pyRepr(string(s)))
	}
	b.WriteString("\n")
	b.WriteString("KNOWN_CONTEXT_SOURCES: Final[frozenset[str]] = frozenset({\n")
	for _, s := range sources {
		fmt.Fprintf(&b, "    %s,\n", contextSourceConstName(string(s)))
	}
	b.WriteString("})\n")
	b.WriteString("\n")
	b.WriteString("\n")
	b.WriteString("# ─── SanitizerAction closed set ───────────────────────────────────────\n")
	b.WriteString("#\n")
	b.WriteString("# Mirrors Go's `internal/security/sanitize_action.go`. v0.3.0 default is\n")
	b.WriteString("# passthrough; operators may opt into quarantine via deployment config.\n")
	b.WriteString("\n")
	for _, a := range actions {
		fmt.Fprintf(&b, "%s: Final[str] = %s\n", sanitizerActionConstName(a.String()), pyRepr(a.String()))
	}
	b.WriteString("\n")
	b.WriteString("KNOWN_SANITIZER_ACTIONS: Final[frozenset[str]] = frozenset({\n")
	for _, a := range actions {
		fmt.Fprintf(&b, "    %s,\n", sanitizerActionConstName(a.String()))
	}
	b.WriteString("})\n")
	return b.String()
}

func contextSourceConstName(value string) string {
	return "CONTEXT_SOURCE_" + strings.ToUpper(value)
}

func sanitizerActionConstName(value string) string {
	return "SANITIZER_ACTION_" + strings.ToUpper(value)
}

// pyRepr renders s as a Python double-quoted string literal. We avoid
// raw-string forms because Go's regex strings already escape backslashes
// once; doubling that with Python raw-strings would diverge from the Go
// source. The escape table covers the characters that appear in the
// pattern table — extending it for new escapes is cheaper than pulling in
// a JSON encoder for what is conceptually a trivial mapping.
func pyRepr(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}
