// Package security: REST + gRPC rate-limit middleware (RFC 0009 PR 2).
package security

import (
	"context"
	"encoding/json"
	"net/http"
	"regexp"
	"strconv"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

const (
	// AgentIDHeader is the canonical REST header carrying the caller's
	// self-reported agent ID (RFC 0009 §B). Self-reported until token
	// validation lands in Phase 4.
	AgentIDHeader = "X-Agent-ID"

	// AgentIDMetadataKey is the gRPC metadata equivalent of
	// [AgentIDHeader]. gRPC normalises keys to lowercase.
	AgentIDMetadataKey = "x-agent-id"

	// ConsoleAgentID is the self-reported X-Agent-ID the web console
	// attaches to every request (web/src/lib/api.js CONSOLE_AGENT_ID). The
	// server names it here so the orchestrator can wire it as a circuit-
	// breaker exemption (CircuitBreakerConfig.ExemptAgentIDs). The console
	// shares the per-agent rate limiter — it gets its own bucket, distinct
	// from the shared anonymous one (so it neither poisons anonymous nor is
	// caught by the H-01 anonymous-deny when an unrelated agent is
	// quarantined) — but unlike a real agent it must never be quarantined:
	// a console that trips its own 429 ≥5×/10min under normal load would
	// otherwise feed the breaker (denials for non-empty ids are recorded)
	// and 403 the operator's own surface, with no automatic recovery (only
	// the operator-token-gated Unquarantine, which has no console UI). The
	// exemption removes no real protection pre-Phase-4: the id is self-
	// reported and trivially spoofable, so quarantine never gated a
	// determined caller (they rotate ids), and the rate limit + anonymous
	// bucket remain the backstop. Must satisfy [agentIDRegex].
	ConsoleAgentID = "web-console"

	// MaxAgentIDLen bounds the accepted X-Agent-ID length at the
	// middleware boundary (PR #244 round-2 review M-07). 256 is well
	// above any plausible agent ID generated by `make
	// generate-persona-nickname` (those are ~16 chars) and well below
	// any sink amplification threshold (audit log JSON line, map key
	// memory). Without this cap an attacker can ship a multi-KiB
	// header that lands once per request in (a) the per-event-fsynced
	// audit log and (b) the rate-limiter / breaker map keys.
	MaxAgentIDLen = 256
)

// agentIDRegex matches the canonical agent-ID schema enforced
// elsewhere (planner.ResourceIDRegex). Duplicated here rather than
// imported to avoid a security \u2192 planner package dependency on the
// request hot path. PR #244 round-2 review M-07.
var agentIDRegex = regexp.MustCompile(`^[a-z0-9][a-z0-9-]*[a-z0-9]$`)

// validAgentID returns true when id is empty (the documented anonymous
// bucket) OR matches the canonical agent-ID schema and length cap.
// Empty is admitted because /healthz, k8s liveness probes, and
// pre-Phase-4 callers all reach the middleware without an X-Agent-ID
// and must not be 400'd. See:
//   - TestRESTMiddleware_AnonymousAllowedWhenNoQuarantine (steady state)
//   - TestRESTMiddleware_QuarantineActiveBlocksAnonymous (H-01 deny path)
//   - TestRESTMiddleware_AcceptsEmptyAndValidAgentID (M-07 baseline)
func validAgentID(id string) bool {
	if id == "" {
		return true
	}
	if len(id) > MaxAgentIDLen {
		return false
	}
	return agentIDRegex.MatchString(id)
}

// RESTRateLimitMiddleware enforces per-agent rate limits and circuit-
// breaker quarantine on inbound HTTP requests. Calls without an
// `X-Agent-ID` header are bucketed against the limiter's
// `UnauthenticatedID` (so a malicious caller cannot bypass the limiter
// by omitting the header) and emit `rate_limit.unauthenticated_caller`
// security-class audit events via the limiter.
//
// PR #244 review H-01 — quarantine bypass closure: when the breaker is
// wired AND any agent is currently quarantined, anonymous calls (empty
// X-Agent-ID) are denied with 403 / `QUARANTINE_ACTIVE`. Without this
// check a quarantined agent could simply drop its header to bypass
// IsQuarantined (which is keyed on the supplied ID) and re-enter via
// the anonymous bucket. The deny only activates while a quarantine is
// open, so under normal operation /healthz and other anonymous probes
// continue to pass — see TestRESTMiddleware_AnonymousAllowedWhenNoQuarantine
// and TestRESTMiddleware_QuarantineActiveBlocksAnonymous.
//
// Returns 429 with `Retry-After: <window_seconds>` on rate-limit deny,
// 403 with `agent quarantined` body on circuit-breaker deny, 403 with
// `QUARANTINE_ACTIVE` on the H-01 anonymous-deny path.
//
// The middleware is intentionally additive: `nil` limiter or breaker
// is a passthrough. Callers wiring this from cmd/orchestrator must
// construct both in main.go before mounting.
func RESTRateLimitMiddleware(limiter *RateLimiter, breaker *CircuitBreaker) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		if limiter == nil && breaker == nil {
			return next
		}
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			agentID := r.Header.Get(AgentIDHeader)
			// PR #244 round-2 review M-07: bound + validate before the
			// value reaches any sink (audit log, ring map key, breaker
			// map key). Empty stays admitted as the anonymous bucket.
			if !validAgentID(agentID) {
				writeJSONError(w, http.StatusBadRequest, "INVALID_AGENT_ID",
					"X-Agent-ID must be ≤1-256 chars matching ^[a-z0-9][a-z0-9-]*[a-z0-9]$")
				return
			}
			if breaker != nil {
				if agentID == "" && breaker.HasAnyQuarantined() {
					writeJSONError(w, http.StatusForbidden, "QUARANTINE_ACTIVE",
						"anonymous calls are denied while a quarantine is active")
					return
				}
				if agentID != "" && breaker.IsQuarantined(agentID) {
					writeJSONError(w, http.StatusForbidden, "QUARANTINED", "agent is quarantined")
					return
				}
			}
			if limiter != nil && !limiter.Allow(r.Context(), agentID) {
				if breaker != nil && agentID != "" {
					breaker.RecordViolation(r.Context(), agentID, ViolationRateLimit)
				}
				w.Header().Set("Retry-After", strconv.Itoa(limiter.cfg.WindowSeconds))
				writeJSONError(w, http.StatusTooManyRequests, "RATE_LIMITED", "rate limit exceeded")
				return
			}
			next.ServeHTTP(w, r)
		})
	}
}

// GRPCRateLimitInterceptor mirrors [RESTRateLimitMiddleware] for the
// gRPC server. Maps deny outcomes to the canonical gRPC status codes:
// `PermissionDenied` for quarantine, `ResourceExhausted` for rate
// limit (so clients can distinguish a transient back-off from a
// terminal break).
//
// On rate-limit deny the interceptor attaches a `retry-after-seconds`
// gRPC header (initial metadata, via [grpc.SetHeader]) so clients have
// parity with the REST `Retry-After` response header and can back off
// intelligently. Clients read the value with the [grpc.Header] CallOption,
// not [grpc.Trailer]. The contract is pinned by
// TestGRPCInterceptor_RetryAfterDeliveredAsHeaderNotTrailer (ISSUE-0002,
// PR #244 review M-04).
//
// NOTE: only unary RPCs are covered. A streaming interceptor is not
// wired here; if a streaming RPC is added before Phase 4 it will
// bypass the limiter. Tracked as PR #244 review NTH-01.
func GRPCRateLimitInterceptor(limiter *RateLimiter, breaker *CircuitBreaker) grpc.UnaryServerInterceptor {
	return func(ctx context.Context, req any, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (any, error) {
		agentID := agentIDFromIncoming(ctx)
		// PR #244 round-2 review M-07: gRPC parity — reject malformed /
		// overlong x-agent-id metadata before it reaches the limiter
		// or breaker maps. InvalidArgument is the canonical mapping for
		// client-side schema violations.
		if !validAgentID(agentID) {
			return nil, status.Error(codes.InvalidArgument,
				"x-agent-id must be ≤1-256 chars matching ^[a-z0-9][a-z0-9-]*[a-z0-9]$")
		}
		if breaker != nil {
			if agentID == "" && breaker.HasAnyQuarantined() {
				// PR #244 review H-01: same anonymous-deny as the REST
				// path. PermissionDenied is the canonical mapping for
				// quarantine-class refusals.
				return nil, status.Error(codes.PermissionDenied,
					"anonymous calls are denied while a quarantine is active")
			}
			if agentID != "" && breaker.IsQuarantined(agentID) {
				return nil, status.Error(codes.PermissionDenied, "agent is quarantined")
			}
		}
		if limiter != nil && !limiter.Allow(ctx, agentID) {
			if breaker != nil && agentID != "" {
				breaker.RecordViolation(ctx, agentID, ViolationRateLimit)
			}
			_ = grpc.SetHeader(ctx, metadata.Pairs(
				"retry-after-seconds", strconv.Itoa(limiter.cfg.WindowSeconds),
			))
			return nil, status.Error(codes.ResourceExhausted, "rate limit exceeded")
		}
		return handler(ctx, req)
	}
}

func agentIDFromIncoming(ctx context.Context) string {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return ""
	}
	if vals := md.Get(AgentIDMetadataKey); len(vals) > 0 {
		return vals[0]
	}
	return ""
}

func writeJSONError(w http.ResponseWriter, status int, code, msg string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]any{
		"error": map[string]string{
			"code":    code,
			"message": msg,
		},
	})
}
