#!/usr/bin/env python3
"""Generate FILEMAP.md from git-tracked files.

Produces a tree-style map of all files tracked by git, making it easy for
AI assistants to understand the repository structure at a glance.

The output file (``FILEMAP.md``) is intended to be committed alongside
code changes.  The pre-commit hook calls this script automatically so the
map stays in sync with the actual file tree.

Usage::

    python scripts/generate_filemap.py          # write FILEMAP.md
    python scripts/generate_filemap.py --check  # exit 1 if FILEMAP.md is stale

Requires: git on PATH.  Uses only Python stdlib.
"""

from __future__ import annotations

import argparse
import subprocess
from collections import defaultdict
from datetime import date
from pathlib import Path, PurePosixPath

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_FILE = REPO_ROOT / "FILEMAP.md"


def _get_tracked_files() -> list[str]:
    """Return sorted list of git-tracked file paths (forward-slash separated)."""
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    files = [f for f in result.stdout.strip().splitlines() if f]
    return sorted(files)


def _build_tree(files: list[str]) -> dict:
    """Build a nested dict representing the directory tree."""
    tree: dict = {}
    for filepath in files:
        parts = PurePosixPath(filepath).parts
        node = tree
        for part in parts[:-1]:
            node = node.setdefault(part + "/", {})
        # Leaf file — store as key with None value
        node[parts[-1]] = None
    return tree


def _render_tree(tree: dict, prefix: str = "") -> list[str]:
    """Render tree dict into indented lines."""
    lines: list[str] = []
    entries = list(tree.items())
    for i, (name, subtree) in enumerate(entries):
        is_last = i == len(entries) - 1
        connector = "└── " if is_last else "├── "
        lines.append(f"{prefix}{connector}{name}")
        if subtree is not None:
            extension = "    " if is_last else "│   "
            lines.extend(_render_tree(subtree, prefix + extension))
    return lines


def _count_by_extension(files: list[str]) -> dict[str, int]:
    """Count files grouped by extension."""
    counts: dict[str, int] = defaultdict(int)
    for f in files:
        ext = PurePosixPath(f).suffix or "(no extension)"
        counts[ext] += 1
    return dict(sorted(counts.items(), key=lambda x: -x[1]))


def _count_top_dirs(files: list[str]) -> dict[str, int]:
    """Count files per top-level directory."""
    counts: dict[str, int] = defaultdict(int)
    for f in files:
        parts = PurePosixPath(f).parts
        top = parts[0] + "/" if len(parts) > 1 else "(root)"
        counts[top] += 1
    return dict(sorted(counts.items(), key=lambda x: -x[1]))


def generate_filemap() -> str:
    """Generate the full FILEMAP.md content."""
    files = _get_tracked_files()
    tree = _build_tree(files)
    tree_lines = _render_tree(tree)

    ext_counts = _count_by_extension(files)
    dir_counts = _count_top_dirs(files)

    today = date.today().isoformat()

    lines = [
        "# Repository File Map",
        "",
        f"> Auto-generated by `scripts/generate_filemap.py` — {today}  ",
        f"> **{len(files)}** tracked files",
        "",
        "## Summary",
        "",
        "| Top-level directory | Files |",
        "|---------------------|-------|",
    ]
    for dirname, count in dir_counts.items():
        lines.append(f"| `{dirname}` | {count} |")

    lines += [
        "",
        "| Extension | Count |",
        "|-----------|-------|",
    ]
    for ext, count in ext_counts.items():
        lines.append(f"| `{ext}` | {count} |")

    lines += [
        "",
        "## Tree",
        "",
        "```",
    ]
    lines.extend(tree_lines)
    lines += [
        "```",
        "",
    ]

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate FILEMAP.md from git-tracked files.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if FILEMAP.md is up-to-date (exit 1 if stale).",
    )
    args = parser.parse_args(argv)

    content = generate_filemap()

    if args.check:
        if not OUTPUT_FILE.is_file():
            print("[FAIL] FILEMAP.md does not exist. Run: python scripts/generate_filemap.py")
            return 1
        existing = OUTPUT_FILE.read_text(encoding="utf-8")
        if existing != content:
            print("[FAIL] FILEMAP.md is stale. Run: python scripts/generate_filemap.py")
            return 1
        print("[OK] FILEMAP.md is up-to-date.")
        return 0

    # newline="\n" forces LF on write regardless of platform. Use Path.open()
    # rather than Path.write_text(newline=...) — the latter kwarg is 3.10+, but
    # the pre-commit hook resolves whatever `python3` is on PATH (which can be
    # 3.9). Path.open() has accepted `newline` for far longer.
    with OUTPUT_FILE.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    print(f"[OK] FILEMAP.md updated ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
