#!/usr/bin/env python3
"""Install the pre-commit hook into ``.git/hooks/pre-commit``.

Creates (or overwrites with ``--force``) a hook script that delegates to
``python scripts/pre_commit.py``.  The generated hook works on Windows
(Git for Windows), macOS, and Linux.

Usage::

    python scripts/install_hooks.py [--force]

Options:
    --force   Overwrite an existing hook without prompting.
"""

from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.checks import ensure_utf8_streams  # noqa: E402

HOOK_PATH = REPO_ROOT / ".git" / "hooks" / "pre-commit"

HOOK_CONTENT = """\
#!/usr/bin/env bash
# Auto-generated by scripts/install_hooks.py — do not edit manually.
# To regenerate: python scripts/install_hooks.py --force
# On Windows (Git Bash) set PYTHON=python if python3 is not available.

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT" || exit 1

PYTHON="${PYTHON:-$(command -v python3 || command -v python)}"
"$PYTHON" scripts/pre_commit.py
"""


def main(argv: list[str] | None = None) -> int:
    ensure_utf8_streams()

    parser = argparse.ArgumentParser(description="Install the pre-commit hook.")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing hook.")
    args = parser.parse_args(argv)

    if not (REPO_ROOT / ".git").is_dir():
        print("Error: .git directory not found. Run this from the repo root.", file=sys.stderr)
        return 1

    HOOK_PATH.parent.mkdir(parents=True, exist_ok=True)

    if HOOK_PATH.exists() and not args.force:
        print(f"Hook already exists at: {HOOK_PATH}")
        print("Use --force to overwrite.")
        return 1

    HOOK_PATH.write_text(HOOK_CONTENT, encoding="utf-8", newline="\n")

    if os.name != "nt":
        st = HOOK_PATH.stat()
        HOOK_PATH.chmod(st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"✓ Pre-commit hook installed at: {HOOK_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
