#!/usr/bin/env python3
"""Install the pre-commit hook into ``.git/hooks/pre-commit``.

Creates (or overwrites with ``--force``) a hook script that delegates to
``python scripts/pre_commit.py``.  The generated hook works on Windows
(Git for Windows), macOS, and Linux.

Usage::

    python scripts/install_hooks.py [--force]

Options:
    --force   Overwrite an existing hook without prompting.
"""

from __future__ import annotations

import argparse
import os
import stat
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.checks import ensure_utf8_streams  # noqa: E402


def _hooks_dir() -> Path:
    """Return the directory git actually reads hooks from.

    Not ``REPO_ROOT / ".git" / "hooks"``: inside a linked worktree
    ``<worktree>/.git`` is a *file* (a gitdir pointer), so that form both
    fails the is-a-directory guard and names a path git never reads. Hooks
    live in the common git dir, which every worktree shares.

    ``git rev-parse --git-path hooks`` resolves the effective location in one
    call — it returns the common dir's ``hooks`` from a linked worktree and
    honours a ``core.hooksPath`` override. The path is relative to the repo
    root when git is run there, so relative results are anchored to
    :data:`REPO_ROOT`.
    """
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return REPO_ROOT / ".git" / "hooks"
    if not out:
        return REPO_ROOT / ".git" / "hooks"
    hooks = Path(out)
    return hooks if hooks.is_absolute() else REPO_ROOT / hooks


HOOK_PATH = _hooks_dir() / "pre-commit"

HOOK_CONTENT = """\
#!/usr/bin/env bash
# Auto-generated by scripts/install_hooks.py — do not edit manually.
# To regenerate: python scripts/install_hooks.py --force

# Resolve the working tree THIS commit belongs to.
#
# `$0` is not usable for that: linked worktrees share the main checkout's
# `.git/hooks` directory, so `dirname "$0"/../..` resolves to the MAIN
# checkout no matter which worktree is committing. The hook would then
# regenerate FILEMAP.md against the main checkout's path while `git ls-files`
# and `git add` act on the committing worktree's index (GIT_DIR /
# GIT_INDEX_FILE are inherited) — writing one tree's file map into the other
# tree's working copy and leaving the main checkout dirty and wrong.
#
# `git rev-parse --show-toplevel` reads the inherited GIT_DIR and returns the
# committing worktree every time, main or linked.
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$REPO_ROOT" ]; then
    REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
fi
cd "$REPO_ROOT" || exit 1

if [ -z "${PYTHON:-}" ]; then
    if command -v python3 >/dev/null 2>&1; then
        PYTHON=python3
    elif command -v python >/dev/null 2>&1; then
        PYTHON=python
    else
        echo "Error: Python not found. Set PYTHON env var." >&2
        exit 1
    fi
fi
"$PYTHON" scripts/pre_commit.py
"""


def main(argv: list[str] | None = None) -> int:
    ensure_utf8_streams()

    parser = argparse.ArgumentParser(description="Install the pre-commit hook.")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing hook.")
    args = parser.parse_args(argv)

    # A linked worktree's ``.git`` is a file, so test for the repository
    # rather than for a ``.git`` *directory* — the installer is expected to
    # run from any worktree, and hooks land in the shared common dir either
    # way.
    if not (REPO_ROOT / ".git").exists():
        print("Error: not a git repository. Run this from the repo root.", file=sys.stderr)
        return 1

    HOOK_PATH.parent.mkdir(parents=True, exist_ok=True)

    if HOOK_PATH.exists() and not args.force:
        print(f"Hook already exists at: {HOOK_PATH}")
        print("Use --force to overwrite.")
        return 1

    # newline="\n" keeps the hook LF-terminated (a CRLF shebang line breaks the
    # hook under Git for Windows' bash). Path.open() rather than
    # Path.write_text(newline=...) so this installer runs under a 3.9 `python3`
    # too — the kwarg form is 3.10+.
    with HOOK_PATH.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(HOOK_CONTENT)

    if os.name != "nt":
        st = HOOK_PATH.stat()
        HOOK_PATH.chmod(st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"✓ Pre-commit hook installed at: {HOOK_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
