#!/usr/bin/env python3
"""Install the pre-commit hook where git actually reads hooks from.

Creates (or overwrites with ``--force``) a hook script that delegates to
``python scripts/pre_commit.py``.  The generated hook works on Windows
(Git for Windows), macOS, and Linux.

The destination is resolved per invocation rather than assumed to be
``.git/hooks/``: every linked worktree shares the main checkout's hooks
directory, and ``core.hooksPath`` overrides it outright.  Run this from any
worktree — the path it reports is the one git will read.

Usage::

    python scripts/install_hooks.py [--force]

Options:
    --force   Overwrite an existing hook without prompting.
"""

from __future__ import annotations

import argparse
import os
import stat
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.checks import ensure_utf8_streams  # noqa: E402

# Variables through which git inherits *which repository* it is operating on.
# They must not leak into the resolution below: git honours them over ``cwd``,
# so an installer run from inside another hook, `git rebase -x`, or
# `git bisect run` would otherwise resolve — and install into — whichever
# repository git was already working on. Deliberately narrow: config- and
# transport-level GIT_* variables are left alone, because `core.hooksPath` may
# legitimately arrive through `GIT_CONFIG_GLOBAL`.
_GIT_REPO_LOCATION_VARS = (
    "GIT_DIR",
    "GIT_WORK_TREE",
    "GIT_COMMON_DIR",
    "GIT_INDEX_FILE",
)

# Generous: this is a local metadata read, so anything approaching it means
# git is wedged rather than slow, and the caller wants an answer either way.
_GIT_TIMEOUT_S = 10


def _hooks_dir() -> Path | None:
    """Return the directory git actually reads hooks from, or ``None``.

    Not ``REPO_ROOT / ".git" / "hooks"``: inside a linked worktree
    ``<worktree>/.git`` is a *file* (a gitdir pointer), so that form both
    fails the is-a-directory guard and names a path git never reads. Hooks
    live in the common git dir, which every worktree shares.

    ``git rev-parse --git-path hooks`` resolves the effective location in one
    call — it returns the common dir's ``hooks`` from a linked worktree and
    honours a ``core.hooksPath`` override. The path is relative to the repo
    root when git is run there, so relative results are anchored to
    :data:`REPO_ROOT`.

    ``None`` means git could not answer — not installed, not a repository, or
    refusing it (``detected dubious ownership`` is the common one). There is
    deliberately no filesystem fallback: the obvious guess is wrong in exactly
    the case this function exists for, since in a linked worktree
    ``REPO_ROOT / ".git"`` is a *file* and creating ``hooks`` beneath it raises
    ``NotADirectoryError``. Callers report the failure instead of guessing.
    """
    env = {k: v for k, v in os.environ.items() if k not in _GIT_REPO_LOCATION_VARS}
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks"],
            cwd=REPO_ROOT,
            capture_output=True,
            # Explicit codec rather than ``text=True``: that decodes with the
            # locale encoding and raises UnicodeDecodeError, which derives from
            # ValueError and so escapes the except clause below entirely.
            encoding="utf-8",
            errors="replace",
            check=True,
            # A hung git (index.lock contention, a network-backed checkout, a
            # credential helper prompting on stdin) must not block forever.
            # TimeoutExpired is a SubprocessError, so it lands in the same
            # fallback as any other failure.
            timeout=_GIT_TIMEOUT_S,
            env=env,
        ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return None
    if not out:
        return None
    hooks = Path(out)
    return hooks if hooks.is_absolute() else REPO_ROOT / hooks


def installed_hook_path() -> Path | None:
    """Return the path git reads the pre-commit hook from, or ``None``.

    The public counterpart to :func:`_hooks_dir`, for callers that need to
    inspect the *installed* hook — notably ``scripts/pre_commit.py``, which
    compares it against :data:`HOOK_CONTENT` to spot a stale install.
    """
    hooks = _hooks_dir()
    return None if hooks is None else hooks / "pre-commit"


HOOK_CONTENT = """\
#!/usr/bin/env bash
# Auto-generated by scripts/install_hooks.py — do not edit manually.
# To regenerate: python scripts/install_hooks.py --force

# Resolve the working tree THIS commit belongs to.
#
# `$0` is not usable for that: linked worktrees share the main checkout's
# `.git/hooks` directory, so `dirname "$0"/../..` resolves to the MAIN
# checkout no matter which worktree is committing. The hook would then
# regenerate FILEMAP.md against the main checkout's path while `git ls-files`
# and `git add` act on the committing worktree's index (GIT_DIR /
# GIT_INDEX_FILE are inherited) — writing one tree's file map into the other
# tree's working copy and leaving the main checkout dirty and wrong.
#
# `git rev-parse --show-toplevel` reads the inherited GIT_DIR and returns the
# committing worktree every time, main or linked.
REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$REPO_ROOT" ]; then
    REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
fi
cd "$REPO_ROOT" || exit 1

# The hook is shared across every worktree, but the script it delegates to is
# tracked content and so varies per branch. A worktree checked out on a branch
# that predates scripts/pre_commit.py (or an orphan/docs-only branch) has no
# copy to run — skip rather than reject the commit with a bare interpreter
# error naming a file the author never expected to need.
if [ ! -f scripts/pre_commit.py ]; then
    echo "pre-commit: no scripts/pre_commit.py on this branch — skipping checks." >&2
    exit 0
fi

if [ -z "${PYTHON:-}" ]; then
    if command -v python3 >/dev/null 2>&1; then
        PYTHON=python3
    elif command -v python >/dev/null 2>&1; then
        PYTHON=python
    else
        echo "Error: Python not found. Set PYTHON env var." >&2
        exit 1
    fi
fi
"$PYTHON" scripts/pre_commit.py
"""


def main(argv: list[str] | None = None) -> int:
    ensure_utf8_streams()

    parser = argparse.ArgumentParser(description="Install the pre-commit hook.")
    parser.add_argument("--force", action="store_true", help="Overwrite an existing hook.")
    args = parser.parse_args(argv)

    # git's own answer is the repository check: it resolves the hooks
    # directory from any worktree, main or linked, and a failure to resolve is
    # exactly the not-a-repository case. A separate ``.git`` probe would be a
    # second, weaker mechanism that disagrees with this one — it passes on a
    # linked worktree's ``.git`` *file* and would send the writes below into a
    # path git never reads.
    hooks_dir = _hooks_dir()
    if hooks_dir is None:
        print(
            "Error: could not resolve this repository's hooks directory. "
            "Is git installed, and is this a git repository?",
            file=sys.stderr,
        )
        return 1

    hook_path = hooks_dir / "pre-commit"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    if hook_path.exists() and not args.force:
        print(f"Hook already exists at: {hook_path}")
        print("Use --force to overwrite.")
        return 1

    # newline="\n" keeps the hook LF-terminated (a CRLF shebang line breaks the
    # hook under Git for Windows' bash). Path.open() rather than
    # Path.write_text(newline=...) so this installer runs under a 3.9 `python3`
    # too — the kwarg form is 3.10+.
    with hook_path.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(HOOK_CONTENT)

    if os.name != "nt":
        st = hook_path.stat()
        hook_path.chmod(st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"✓ Pre-commit hook installed at: {hook_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
