#!/usr/bin/env python3
"""Regenerate ``docs/merged-prs.md`` from the squash-merge subjects on ``main``.

ROADMAP.md carried this table by hand until 2026-09-06. It stopped at #708 in
June while ~150 PRs merged after it — derivable data typed by hand goes
stale. Every squash merge leaves ``<title> (#N)`` as its subject, so the
history is a ``git log`` away; this script writes it between auto markers,
the same shape as ``docs/rfcs/INDEX.md`` and ``docs/issues/INDEX.md``, and
``--check`` fails when the file is behind the log.

Usage::

    python scripts/merged_prs.py            # write docs/merged-prs.md
    python scripts/merged_prs.py --check    # exit 1 if stale
    python scripts/merged_prs.py --print    # write, and print the table

The pre-commit hook regenerates it (so the first commit after a merge carries
the new row); the ``Docs hygiene`` CI job runs ``--check``.

``--check`` is deliberately looser than the RFC / issue index checks: the
committed file can never contain the squash merge that lands it, so a
byte-exact check would fail on every push to ``main`` and then on every PR
until one regenerated. The check therefore passes when the committed rows
are a *suffix* of the generated rows — behind by the newest merges only —
and fails on anything else (a hand edit, a format change, a lost row). The
hook catches the file up on the next commit anywhere.

Requires: git on PATH. Uses only Python stdlib.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
_SCRIPTS_DIR = Path(__file__).resolve().parent
for _p in (str(REPO_ROOT), str(_SCRIPTS_DIR)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from _doc_index import REPO_URL, run_index_cli  # noqa: E402  (same style as rfcs.py / issues.py)

from scripts._git import git_output  # noqa: E402

OUTPUT_FILE = REPO_ROOT / "docs" / "merged-prs.md"
BEGIN_MARKER = "<!-- BEGIN merged-prs:auto -->"
END_MARKER = "<!-- END merged-prs:auto -->"

_SUBJECT_RE = re.compile(r"^(?P<title>.*?)\s*\(#(?P<number>\d+)\)$")
_SCOPE_RE = re.compile(r"^[a-z]+\(([^)]*)\)")
_RFC_RE = re.compile(r"\bRFC[ -]?0*(\d{4})\b", re.I)
_ISSUE_RE = re.compile(r"\bISSUE-(\d{4})\b")
_VERSION_RE = re.compile(r"\bv(\d+\.\d+\.\d+)\b")
_SCOPE_VERSION_RE = re.compile(r"^v(\d)(\d)(\d{1,2})$")


@dataclass(frozen=True)
class MergedPR:
    number: int
    date: str
    title: str


def parse_log(log: str) -> list[MergedPR]:
    """``hash|date|subject`` lines → squash-merged PRs, in log order (newest first).

    One row per PR number: a branch commit that quotes a PR number in its
    subject ("follow-up (#844)") sits on a feature branch's first-parent
    chain locally, and must not produce a second row for #844.
    """
    prs: list[MergedPR] = []
    seen: set[int] = set()
    for line in log.splitlines():
        parts = line.split("|", 2)
        if len(parts) != 3:
            continue
        _, date, subject = parts
        m = _SUBJECT_RE.match(subject.strip())
        if not m:
            continue
        number = int(m.group("number"))
        if number in seen:
            continue
        seen.add(number)
        prs.append(MergedPR(number=number, date=date, title=m.group("title")))
    return prs


def _rows(content: str) -> list[str]:
    """The table rows between the auto markers, in order."""
    m = re.search(re.escape(BEGIN_MARKER) + r"\n(.*?)" + re.escape(END_MARKER), content, re.S)
    if not m:
        return []
    return [ln for ln in m.group(1).splitlines() if ln.startswith("| [#")]


def behind_by(committed: str, generated: str) -> int | None:
    """How many newest rows the committed file lacks, or ``None`` if it differs otherwise.

    ``0`` means identical rows; ``N > 0`` means the committed rows are exactly
    the generated rows minus the newest ``N`` (the file predates those
    merges); ``None`` means the committed file is not a suffix — hand-edited,
    generated by an older format, or missing an older row.
    """
    have, want = _rows(committed), _rows(generated)
    if len(have) > len(want):
        return None
    n = len(want) - len(have)
    return n if want[n:] == have else None


def compare(committed: str, generated: str) -> str | None:
    """``None`` when fresh enough for ``--check``; otherwise the reason."""
    n = behind_by(committed, generated)
    if n is None:
        return "does not match the generated table (hand edit or format drift)"
    return None


def _version_from_scope(scope: str) -> str | None:
    """``v0315`` → ``v0.3.15`` (major, minor, patch digits); the cycle-prefix convention."""
    for token in scope.split(","):
        m = _SCOPE_VERSION_RE.match(token.strip())
        if m:
            return f"v{m.group(1)}.{m.group(2)}.{int(m.group(3))}"
    return None


def classify(title: str) -> str:
    """Derive the Area column from a subject: RFCs, issues, version, or scope."""
    scope_m = _SCOPE_RE.match(title)
    scope = scope_m.group(1) if scope_m else ""
    version = None
    vm = _VERSION_RE.search(title)
    if vm:
        version = f"v{vm.group(1)}"
    elif scope:
        version = _version_from_scope(scope)

    parts: list[str] = []
    rfcs = sorted({f"RFC {n}" for n in _RFC_RE.findall(title)})
    issues = sorted({f"ISSUE-{n}" for n in _ISSUE_RE.findall(title)})
    if rfcs:
        parts.append(", ".join(rfcs))
    if issues:
        parts.append(", ".join(issues))
    if version:
        lowered = title.lower()
        if "release-prep" in lowered or "release prep" in lowered:
            parts.append(f"{version} release prep")
        elif "post-release" in lowered:
            parts.append(f"{version} post-release")
        else:
            parts.append(version)
    if parts:
        return " · ".join(parts)
    if scope and not _SCOPE_VERSION_RE.match(scope):
        return ", ".join(s.strip() for s in scope.split(","))
    return "—"


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def render(prs: list[MergedPR]) -> str:
    rows = [
        f"| [#{p.number}]({REPO_URL}/pull/{p.number}) | {_cell(p.title)} | "
        f"{_cell(classify(p.title))} | {p.date} |"
        for p in prs
    ]
    table = "\n".join(rows) + ("\n" if rows else "")
    return (
        "# Persatrix — Merged PR History\n\n"
        f"> {len(prs)} merged · newest first · auto-generated by `make merged-prs` from the\n"
        "> squash-merge subjects on `main` (do not hand-edit between markers).\n"
        "> Lived in ROADMAP.md until 2026-09-06, where it had stopped at #708.\n\n"
        "The Area column is derived from the title: RFC and issue IDs, the version\n"
        "(from a `vX.Y.Z` in the title or a `vNNN` scope), release-prep / post-release\n"
        "markers, else the Conventional Commit scope.\n\n"
        f"{BEGIN_MARKER}\n"
        "| PR | Title | Area | Date |\n"
        "|----|-------|------|------|\n"
        f"{table}"
        f"{END_MARKER}\n"
    )


def _build() -> tuple[str, int, list[str]]:
    log = git_output(REPO_ROOT, "log", "--first-parent", "--format=%h|%as|%s")
    if log is None:
        return "", 0, ["git log failed — is this a git checkout with history?"]
    prs = parse_log(log)
    return render(prs), len(prs), []


def main() -> int:
    return run_index_cli(
        description="Regenerate docs/merged-prs.md from squash-merge subjects.",
        index_file=OUTPUT_FILE,
        repo_root=REPO_ROOT,
        build_content=_build,
        make_target="merged-prs",
        compare=compare,
    )


if __name__ == "__main__":
    raise SystemExit(main())
