"""``generate_filemap.py --check`` must be date-insensitive (ISSUE-0133).

The generated header carries the generation date. A freshness check that
compared bytes would therefore fail in CI on any day other than the one the
map was committed — every PR older than a day would go red on a file it
never touched. The check compares everything *except* that date.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from scripts import generate_filemap
from scripts.generate_filemap import _comparable

HEADER_A = (
    "# Repository File Map\n\n"
    "> Auto-generated by `scripts/generate_filemap.py` — 2026-09-06  \n"
    "> **2073** tracked files\n"
)
HEADER_B = HEADER_A.replace("2026-09-06", "2026-09-07")


def test_only_the_date_line_is_ignored() -> None:
    assert _comparable(HEADER_A) == _comparable(HEADER_B)


def test_a_changed_file_count_is_still_a_difference() -> None:
    assert _comparable(HEADER_A) != _comparable(HEADER_A.replace("2073", "2074"))


def test_a_changed_tree_is_still_a_difference() -> None:
    assert _comparable(HEADER_A + "a/b.py\n") != _comparable(HEADER_A + "a/c.py\n")


def test_the_writer_keeps_the_committed_date_when_only_the_date_would_change(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str],
) -> None:
    """The hook regenerates on every commit; a date-only diff is churn."""
    out = tmp_path / "FILEMAP.md"
    out.write_text(HEADER_A, encoding="utf-8")
    monkeypatch.setattr(generate_filemap, "OUTPUT_FILE", out)
    monkeypatch.setattr(generate_filemap, "generate_filemap", lambda: HEADER_B)

    assert generate_filemap.main([]) == 0
    assert out.read_text(encoding="utf-8") == HEADER_A
    assert "unchanged" in capsys.readouterr().out


def test_the_writer_still_writes_a_real_change(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    out = tmp_path / "FILEMAP.md"
    out.write_text(HEADER_A, encoding="utf-8")
    monkeypatch.setattr(generate_filemap, "OUTPUT_FILE", out)
    monkeypatch.setattr(generate_filemap, "generate_filemap", lambda: HEADER_B + "a/b.py\n")

    assert generate_filemap.main([]) == 0
    assert out.read_text(encoding="utf-8") == HEADER_B + "a/b.py\n"
