"""``generate_filemap.py --check`` must be date-insensitive (ISSUE-0133).

The generated header carries the generation date. A freshness check that
compared bytes would therefore fail in CI on any day other than the one the
map was committed — every PR older than a day would go red on a file it
never touched. The check compares everything *except* that date.
"""

from __future__ import annotations

from scripts.generate_filemap import _comparable

HEADER_A = (
    "# Repository File Map\n\n"
    "> Auto-generated by `scripts/generate_filemap.py` — 2026-09-06  \n"
    "> **2073** tracked files\n"
)
HEADER_B = HEADER_A.replace("2026-09-06", "2026-09-07")


def test_only_the_date_line_is_ignored() -> None:
    assert _comparable(HEADER_A) == _comparable(HEADER_B)


def test_a_changed_file_count_is_still_a_difference() -> None:
    assert _comparable(HEADER_A) != _comparable(HEADER_A.replace("2073", "2074"))


def test_a_changed_tree_is_still_a_difference() -> None:
    assert _comparable(HEADER_A + "a/b.py\n") != _comparable(HEADER_A + "a/c.py\n")
