"""Pin CI's Python installs to the committed constraints file.

CI used to install the agents' dependencies with a bare `pip install -e
".[dev]"`, which takes the newest release PyPI has at that minute. On
2026-09-25 OpenTelemetry 1.45.0 reached PyPI and three minutes later the
required Python job failed on every open PR, whatever the PR changed (#1002).
CI now installs at the versions in `.github/python-constraints.txt`, so a new
release reaches CI only through a reviewed change to that file.

These tests pin the parts that make that true: the file covers every
dependency `agents/pyproject.toml` declares, the one install command passes
it, no workflow installs around that command, and the required Python job
fails a PR whose file no longer matches `agents/pyproject.toml`.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

import yaml
from _test_infra import ci_job_steps, makefile_recipe_body
from packaging.requirements import Requirement

REPO_ROOT = Path(__file__).resolve().parents[3]
CONSTRAINTS = REPO_ROOT / ".github" / "python-constraints.txt"
WORKFLOWS = REPO_ROOT / ".github" / "workflows"

UV_PIN_RE = re.compile(r"^UV_VERSION\s*:=\s*(\d+\.\d+\.\d+)\s*$", re.M)
# A pin line: `name==version`, optionally followed by ` ; marker`.
PIN_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;]+)", re.M)
# A pip install of the agents package itself: its dev extra, the agents
# directory, or an editable install. Installing pip or a tool is fine.
AGENTS_INSTALL_RE = re.compile(r"pip3?\s+install\b[^\n]*(\.\[dev\]|\bagents\b|\s-e\s)")


def _makefile() -> str:
    return (REPO_ROOT / "Makefile").read_text(encoding="utf-8")


def _canonical(name: str) -> str:
    """PEP 503 normalisation, so `PyYAML` and `pyyaml` are one package."""
    return re.sub(r"[-_.]+", "-", name).lower()


def _pins() -> dict[str, list[str]]:
    """Every pinned version per package; a platform split can pin one twice."""
    pins: dict[str, list[str]] = {}
    for name, version in PIN_RE.findall(CONSTRAINTS.read_text(encoding="utf-8")):
        pins.setdefault(_canonical(name), []).append(version)
    return pins


def _declared() -> list[Requirement]:
    """What CI installs: the base dependencies plus the `dev` extra."""
    text = (REPO_ROOT / "agents" / "pyproject.toml").read_text(encoding="utf-8")
    project = tomllib.loads(text)["project"]
    specs = project["dependencies"] + project["optional-dependencies"]["dev"]
    return [Requirement(spec) for spec in specs]


def _workflow_run_scripts() -> list[tuple[str, str]]:
    """(`workflow:job`, script) for every `run:` step in every workflow."""
    scripts = []
    for path in sorted(WORKFLOWS.glob("*.yml")):
        workflow = yaml.safe_load(path.read_text(encoding="utf-8"))
        for job_id, job in (workflow.get("jobs") or {}).items():
            for step in job.get("steps") or []:
                if "run" in step:
                    scripts.append((f"{path.name}:{job_id}", str(step["run"])))
    return scripts


def test_makefile_declares_exactly_one_uv_pin() -> None:
    pins = UV_PIN_RE.findall(_makefile())
    assert len(pins) == 1, f"expected one UV_VERSION := X.Y.Z pin, found {pins}"


def test_constraints_targets_refuse_an_unpinned_uv() -> None:
    """The check diffs uv's output byte for byte, so every target runs the pin."""
    makefile = _makefile()
    for target in ("python-constraints", "python-constraints-upgrade", "python-constraints-check"):
        rule = re.search(rf"^{re.escape(target)}:([^\n#]*)", makefile, re.M)
        assert rule, f"no `{target}` rule in the Makefile"
        assert "python-constraints-uv" in rule.group(1).split(), (
            f"`{target}` does not depend on the uv version check"
        )
    assert "$(UV_VERSION)" in makefile_recipe_body("python-constraints-uv")


def test_constraints_pin_every_declared_dependency_inside_its_range() -> None:
    """The offline half of `make python-constraints-check`: a dependency added
    to agents/pyproject.toml, or a range narrowed there, without re-resolving
    the file fails here with no network and no uv."""
    pins = _pins()
    problems = []
    for req in _declared():
        versions = pins.get(_canonical(req.name))
        if not versions:
            problems.append(f"{req.name} is not pinned")
            continue
        outside = [v for v in versions if not req.specifier.contains(v, prereleases=True)]
        if outside:
            problems.append(f"{req.name} is pinned at {outside}, outside '{req.specifier}'")
    assert not problems, "run `make python-constraints`: " + "; ".join(problems)


def test_constraints_file_names_the_command_that_writes_it() -> None:
    header = CONSTRAINTS.read_text(encoding="utf-8").splitlines()[:2]
    assert header[0].startswith("# This file was autogenerated by uv"), header
    assert header[1].strip() == "#    make python-constraints", header


def test_build_agents_installs_at_the_pinned_versions() -> None:
    """`make build-agents` is the one install command, locally and in CI."""
    assert re.search(
        r"^PYTHON_CONSTRAINTS\s*:=\s*\.github/python-constraints\.txt\s*$", _makefile(), re.M
    ), "PYTHON_CONSTRAINTS does not name .github/python-constraints.txt"
    recipe = makefile_recipe_body("build-agents")
    install = [line for line in recipe.splitlines() if " install " in line]
    assert len(install) == 1, f"expected one pip install line in build-agents, found {install}"
    assert "-c ../$(PYTHON_CONSTRAINTS)" in install[0], "build-agents installs without the pins"


def test_no_workflow_installs_the_agents_package_around_the_pins() -> None:
    """A direct `pip install -e ".[dev]"` takes whatever PyPI has that minute."""
    offenders = [
        where for where, script in _workflow_run_scripts() if AGENTS_INSTALL_RE.search(script)
    ]
    assert not offenders, f"install through `make build-agents` instead: {offenders}"


def test_python_job_checks_the_constraints_with_the_pinned_uv() -> None:
    """The required job reads the Makefile pin, installs exactly it, and runs
    the same target a developer runs."""
    steps = ci_job_steps("python")
    runs = [str(step.get("run", "")) for step in steps]
    reads_pin = [step for step in steps if "make -s uv-version" in str(step.get("run", ""))]
    assert len(reads_pin) == 1, "no step reads the pin with `make -s uv-version`"
    step_id = reads_pin[0].get("id")
    assert step_id, "the pin-reading step needs an id the install step can reference"
    installs = [run for run in runs if f"uv==${{{{ steps.{step_id}.outputs.version }}}}" in run]
    assert len(installs) == 1, "no step installs uv at the version the Makefile step read"
    assert [run.strip() for run in runs].count("make python-constraints-check") == 1, (
        "the python job must run exactly `make python-constraints-check`"
    )
