"""Generated *.pyi parity test (ISSUE-0017).

`agents/generated/*.pyi` files are generated by `mypy-protobuf` (the
`--mypy_out` plugin to `grpc_tools.protoc`) at `make proto-python` time.
They are committed because the agents/ install layout treats
`agents/generated/` as part of the wheel and we want IDE / mypy users
to see the stubs without running protoc locally.

This test asserts that every checked-in `.pyi` is byte-identical to the
output mypy-protobuf would produce now from the corresponding
`proto/*.proto` source. If a contributor edits a `.proto` and forgets
to run `make proto-python`, the freshness gate fails with a precise
pointer to the staleness — same shape as
`test_pattern_parity.py::TestParityFreshness` for the RFC 0009
sanitizer mirror.

Why a freshness gate is necessary
---------------------------------
Before this PR, `agents/generated/*.pyi` were hand-maintained because
the project's protoc invocation did not pass `--mypy_out`. Every proto
change shipped with a hand-edited stub whose drift from the proto was
invisible to mypy and CI: stubs that omit a new field, or carry an old
field as a different type, silently masked real type errors in
downstream agent code. This freshness gate locks the generator output
to the proto.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
PROTO_DIR = REPO_ROOT / "proto"
GENERATED_DIR = REPO_ROOT / "agents" / "generated"


def _have_mypy_protobuf() -> bool:
    try:
        import mypy_protobuf  # noqa: F401
    except ImportError:
        return False
    # The protoc plugin entry point ships as `protoc-gen-mypy` on PATH.
    return shutil.which("protoc-gen-mypy") is not None


def _proto_files() -> list[Path]:
    return sorted(PROTO_DIR.glob("*.proto"))


class TestGeneratedPyiFreshness:
    """Re-running the generator must produce the checked-in `.pyi`
    byte-for-byte. If this fails, run `make proto-python` and commit
    the result.
    """

    @pytest.mark.skipif(
        not _have_mypy_protobuf(),
        reason="mypy-protobuf not installed; freshness check deferred to CI.",
    )
    @pytest.mark.parametrize("proto_file", _proto_files(), ids=lambda p: p.name)
    def test_generator_output_matches_checked_in_pyi(
        self, proto_file: Path, tmp_path: Path
    ) -> None:
        result = subprocess.run(
            [
                sys.executable, "-m", "grpc_tools.protoc",
                f"--mypy_out={tmp_path}",
                f"-I{PROTO_DIR}",
                str(proto_file),
            ],
            cwd=REPO_ROOT,
            capture_output=True,
            check=False,
            text=True,
        )
        if result.returncode != 0:
            pytest.fail(
                f"protoc --mypy_out failed for {proto_file.name} "
                f"(rc={result.returncode}).\n"
                f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
            )

        pyi_name = proto_file.stem + "_pb2.pyi"
        regenerated = tmp_path / pyi_name
        if not regenerated.exists():
            pytest.fail(
                f"protoc --mypy_out produced no {pyi_name} in {tmp_path}; "
                f"contents: {list(tmp_path.iterdir())}"
            )

        committed = GENERATED_DIR / pyi_name
        if not committed.exists():
            pytest.fail(
                f"agents/generated/{pyi_name} is missing. Run:\n"
                f"    make proto-python\n"
                f"and commit the resulting file."
            )

        # Normalise CRLF → LF so Windows checkouts (where
        # ``core.autocrlf=true`` rewrites LF to CRLF on checkout)
        # compare equal to the ``protoc``-emitted LF bytes. CI runs
        # on Linux where the bytes already match; the normalisation
        # is purely for local-dev parity.
        if committed.read_bytes().replace(b"\r\n", b"\n") != regenerated.read_bytes().replace(b"\r\n", b"\n"):
            pytest.fail(
                f"agents/generated/{pyi_name} is stale relative to "
                f"proto/{proto_file.name}. Run:\n"
                f"    make proto-python\n"
                f"and commit the resulting diff."
            )
