# Code generated by cmd/genpatterns. DO NOT EDIT.
#
# Source: internal/security/sanitize_patterns.go (var DefaultPatterns).
# Regenerate via: make generate-sanitizer-patterns
#
# Pattern parity is enforced by tests/unit/python/test_pattern_parity.py.
# If this file goes stale relative to the Go source, the parity test
# fails until the generator is re-run and the diff committed.

from __future__ import annotations

import re
from dataclasses import dataclass


@dataclass(frozen=True)
class _Pattern:
    name: str
    regex: str
    description: str


# DEFAULT_PATTERNS mirrors security.DefaultPatterns from the Go side.
# Order, names, regex strings, and descriptions are byte-identical.
DEFAULT_PATTERNS: list[_Pattern] = [
    _Pattern(
        name="instruction_override",
        regex="(?i)\\bignore\\s+(?:all\\s+)?previous\\s+instructions?\\b",
        description="Phrase asking the model to disregard prior instructions wholesale.",
    ),
    _Pattern(
        name="instruction_override",
        regex="(?i)\\bdisregard\\s+(?:everything|all|the)\\b",
        description="Variant phrasing of instruction override.",
    ),
    _Pattern(
        name="instruction_override",
        regex="(?i)\\bnew\\s+instructions\\s*:",
        description="Attempt to inject a fresh instruction block via a labelled prefix.",
    ),
    _Pattern(
        name="instruction_override",
        regex="(?i)\\bsystem\\s+prompt\\s*:",
        description="Attempt to spoof a fresh system-prompt block.",
    ),
    _Pattern(
        name="role_injection",
        regex="(?i)\\byou\\s+are\\s+now\\b",
        description="Attempt to redefine the agent's role mid-context.",
    ),
    _Pattern(
        name="role_injection",
        regex="(?i)\\bact\\s+as\\b",
        description="Attempt to coerce a role swap.",
    ),
    _Pattern(
        name="role_injection",
        regex="(?i)\\bpretend\\s+to\\s+be\\b",
        description="Attempt to coerce a role swap via roleplay framing.",
    ),
    _Pattern(
        name="role_injection",
        regex="(?i)\\bforget\\s+you\\s+are\\b",
        description="Attempt to clear the agent's identity preamble.",
    ),
    _Pattern(
        name="exfiltration",
        regex="(?i)\\bsend\\b.{0,50}\\bto\\b\\s+\\S+\\.(?:com|net|org|io|test|example)",
        description="Bait the agent into sending data to an external host.",
    ),
    _Pattern(
        name="exfiltration",
        regex="(?i)\\boutput\\b.{0,50}\\bhttps?://",
        description="Bait the agent into echoing data to an external URL.",
    ),
    _Pattern(
        name="exfiltration",
        regex="(?i)\\bPOST\\b.{0,50}\\bhttps?://",
        description="Bait the agent into POSTing data to an external URL.",
    ),
]


# Compiled forms are cached at module load. The Go side compiles via
# regexp.MustCompile in package init; the Python equivalent is the
# tuple below, evaluated once when this module is imported.
COMPILED_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = tuple(
    (p.name, re.compile(p.regex)) for p in DEFAULT_PATTERNS
)
