# Code generated by cmd/genpatterns. DO NOT EDIT.
#
# Source:
#   - internal/security/context_source.go (ContextSource closed set)
#   - internal/security/sanitize_action.go (SanitizerAction closed set)
# Regenerate via: make generate-sanitizer-patterns
#
# Enum parity is enforced by tests/unit/python/test_pattern_parity.py.
# Adding or renaming a Go-side enum value without re-running the
# generator fails CI; the byte-level diff is the parity gate.

from __future__ import annotations

from typing import Final

# ─── ContextSource closed set ─────────────────────────────────────────
#
# Mirrors Go's `internal/security/context_source.go`. The string values
# are written verbatim into the audit log's `Detail.source` field on
# both sides, so renaming silently breaks operator alerts.

CONTEXT_SOURCE_INTERNAL: Final[str] = "internal"
CONTEXT_SOURCE_EXTERNAL: Final[str] = "external"
CONTEXT_SOURCE_AGENT_OUTPUT: Final[str] = "agent_output"
CONTEXT_SOURCE_USER: Final[str] = "user"
CONTEXT_SOURCE_CHANNEL_MESSAGE: Final[str] = "channel_message"

KNOWN_CONTEXT_SOURCES: Final[frozenset[str]] = frozenset({
    CONTEXT_SOURCE_INTERNAL,
    CONTEXT_SOURCE_EXTERNAL,
    CONTEXT_SOURCE_AGENT_OUTPUT,
    CONTEXT_SOURCE_USER,
    CONTEXT_SOURCE_CHANNEL_MESSAGE,
})


# ─── SanitizerAction closed set ───────────────────────────────────────
#
# Mirrors Go's `internal/security/sanitize_action.go`. v0.3.0 default is
# passthrough; operators may opt into quarantine via deployment config.

SANITIZER_ACTION_PASSTHROUGH: Final[str] = "passthrough"
SANITIZER_ACTION_QUARANTINE: Final[str] = "quarantine"

KNOWN_SANITIZER_ACTIONS: Final[frozenset[str]] = frozenset({
    SANITIZER_ACTION_PASSTHROUGH,
    SANITIZER_ACTION_QUARANTINE,
})
